######################################################################
#
# File name : mov_aver_tb_compile.do
# Created on: Mon Mar 30 09:58:08 +0300 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib questa_lib/work
vlib questa_lib/msim

vlib questa_lib/msim/xil_defaultlib

vmap xil_defaultlib questa_lib/msim/xil_defaultlib

vcom  -93 -work xil_defaultlib  \
"../../../../MOV_AVER_PR.gen/sources_1/ip/divider/sim/divider.vhd" \

vlog  -incr -mfcu -work xil_defaultlib  \
"../../../../MOV_AVER_PR.gen/sources_1/ip/input_fifo/sim/input_fifo.v" \

vlog  -incr -mfcu -sv -work xil_defaultlib  \
"../../../../../hdl/mov_aver_top.sv" \
"../../../../../tb/mov_aver_tb.sv" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

