# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Viv_prj24.2/MOV_AVER/MOV_AVER_PR/MOV_AVER_PR.srcs/sources_1/ip/divider/divider.xci
# IP: The module: 'divider' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Viv_prj24.2/MOV_AVER/MOV_AVER_PR/MOV_AVER_PR.gen/sources_1/ip/divider/divider_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'divider'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Viv_prj24.2/MOV_AVER/MOV_AVER_PR/MOV_AVER_PR.srcs/sources_1/ip/divider/divider.xci
# IP: The module: 'divider' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Viv_prj24.2/MOV_AVER/MOV_AVER_PR/MOV_AVER_PR.gen/sources_1/ip/divider/divider_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'divider'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
